package rules

import cn.iocoder.engine.drools.model.Address;
import cn.iocoder.engine.drools.model.fact.AddressCheckResult;

rule "Postcode should be filled with exactly 5 numbers"
    when
        address : Address(postcode != null, postcode matches "([0-9]{5})")
        checkResult : AddressCheckResult()
    then
        checkResult.setPostCodeResult(true);
		System.out.println("规则中打印日志：校验通过!");
end

//rule "address print"
//    when
//        $p : Address()
//    then
//        System.out.println( "Address " + $p );
//end

//rule "address judge"
//    when
//        p: Address( postcode=="haha" )
//    then
//        p.postcode = "other";
//        System.out.println("Address.postcode" +p.name);
//
//        System.out.println("Address" + p);
//end